---
title: " "
listing:
  - id: current
    include: 
      people_group: "current"
    exclude:
      external: true
    template: ../_ejs/people-box.ejs
    type: grid
    # fields: [title, subtitle, image, education]
    fields: [title, subtitle, image]
  # - id: pi
  #   include:
  #     people_group: "pi"
  #   exclude:
  #     external: true
  #   template: ../_ejs/people-box.ejs
  #   type: grid
  #   fields: [title, subtitle, image, education]
  # - id: researcher
  #   include: 
  #     people_group: "researcher"
  #   exclude:
  #     external: true
  #   template: ../_ejs/people-box.ejs
  #   sort: last
  #   type: grid
  #   fields: [title, subtitle, image, education]
  # - id: postdoc
  #   include: 
  #     people_group: "postdoc"
  #   exclude:
  #     external: true
  #   template: ../_ejs/people-box.ejs
  #   sort: last    
  #   type: grid
  #   fields: [title, subtitle, image, education]
  # - id: gradstudent
  #   include: 
  #     people_group: "gradstudent"
  #   exclude:
  #     external: true
  #   template: ../_ejs/people-box.ejs
  #   sort: last
  #   type: grid
  #   fields: [title, subtitle, image, education]
  # - id: tech
  #   include:
  #     people_group: "tech"
  #   exclude:
  #     external: true
  #   template: ../_ejs/people-box.ejs
  #   sort: last
  #   type: grid
  #   fields: [title, subtitle, image, education]
  - id: alumni
    include:
      people_group: "alumni"
    # exclude:
    #   external: true
  #   template: ../_ejs/alumni-box.ejs
  #   sort: last
  #   type: grid
  #   fields: [title, subtitle, image, education, altsubtitle, alteducation]
# page-layout: full
format:
  html: 
    fontsize: 0.8em
---

## Current Lab Members

::: {#current}
:::

## Information for Prospective Students

If you are interested in joining our lab, [start here](./misc-pages/prospectives.qmd).

<!-- ::: sand-background -->
<!-- ## Principal Investigator -->

<!-- ::: {#pi} -->

<!-- ::: -->

<!-- :::{.sand-background} -->

<!-- ## Research Scientists -->

<!-- ::: {#researcher} -->

<!-- ::: -->

<!-- ::: -->

<!-- :::{.sand-background} -->

<!-- ## Postdoctoral Fellows -->

<!-- ::: {#postdoc} -->

<!-- ::: -->

<!-- :::{.sand-background} -->

<!-- ## Graduate Students -->

<!-- ::: {#gradstudent} -->

<!-- ::: -->

<!-- ::: -->

<!-- :::{.sand-background} -->

<!-- ## Post Baccalaureate Researchers -->

<!-- ::: {#post-bac} -->

<!-- ::: -->

<!-- :::{.sand-background} -->

## Lab Alumni

<!-- ::: {#alumni} -->
<!-- ::: -->

### Postdoctoral Scholars  

- **Eric Scott:** Lagged effects of climate and habitat fragmentation on *H. acuminata* demography.  

- **Maria Rosa Darrigo:** *Science Without Borders Postdoctoral Fellow*, Variation in avian dispersal ability and *H. acuminata* demography. 

- **Paul Gagnon:** The cumulative effects of chronically reduced plant growth in forest fragments. 
 
- **Heather Passmore:** Effect of forest fragmentation on the structure of Amazonian ant-plant mutualist networks. 
 
- **Thiago Izzo:** Population dynamics of ant-plant mutualist systems.  

### Graduate Students

- **Thomas Smith**, Ph.D. in Wildlife Ecology & Conservation, 2023.  
Matrix effects on movement and population dynamics in experimentally fragmented systems. _Co-advised with Dr. Robert Fletcher._

- **Fabiane Mundim**, Ph.D. in Wildlife Ecology & Conservation, 2016.  
Above- and below-ground plant-herbivore interactions in Brazil's Cerrado and how they are influenced by climate change. 

- **Ernane Vieira-Neto**, Ph.D. in Wildlife Ecology & Conservation, 2016.    
The influence of the expansion of road networks in Brazil's Cerrado on the demography and spread of leaf-cutter ants.

- **Elan Simon Parsons**, MA in Latin American Studies, 2018.  
Prevalence and functional form of edge-effects in fragmented landscapes.

- **Ana Cecilia Silva**, M.A. Student in Latin American Studies, 2015.  
How Brazilian’s attitudes regarding extensive executive power influence support for affirmative action.

- **Paulo Rubim**, Ph.D., Universidade Federal de São Carlos, 2013  
Factors influencing _Heliconia acuminata_ distribution and reproduction at multiple spatial scales. _Co-advised with Dr. Dalva Mattos_.

- **Cris Follman Jurinitz**, Ph.D. in Ecology, Universidade de São Paulo, 2012  
Tree demography in primary and regenerating Atlantic rain forests. _Co-advised with Dr. Alexandre Oliveira._

- **Christine Lucas**, Ph.D. in Wildlife Ecology & Conservation, 2010.
Influence of flooding and disturbance from cattle ranching on the regeneration of _Varzea_ forests in the Brazilian Amazon. 

- **Stella Copeland**, M.S. in WEC, 2009.  
Effect of nitrogen enrichment and simulated changes in precipitation on two _Cerrado_ grasses. 

- **Gwen Iacona**, M.S. in WEC, 2008.  
Seedling establishment along productivity gradients in Longleaf Pine savannas. _Co-advised with Dr. Kay Kirkman, Jones Ecological Research Center_. 

- **Pedro Braunger**, M.S. in Biology, Universidade Federal de Uberlândia  
Effect of roads on the diversity of _Cerrado_ plant communities. 

- **Alana Vaz Ferreira**, M.S. in Biology, Universidade Federal de Uberlandia, 2007  
Seed predation by ants, birds, and rodents in Brazil’s _Cerrado_. 

- **Ian Fiske**, M.S. in WEC, 2006  
Sampling in plant demographic studies and the implications for matrix model projections.

- **Matthew Trager**, M.S. in SNRE, 2006  
The effects of nutrient manipulation on ant-plant mutualisms. 

- **Maria Beatriz Nogueira Ribeiro**, M.S. in Ecology, Universidade de São Paulo, 2005  
Plant regeneration in Amazonian secondary forests. 


### Visiting Students

- **Alan Nilo da Costa**, Universidade Federal de Uberlândia  
- **Carolina Ferreira Gomes**, Universidade Federal de Uberlândia   
- **Diego Resende**, Universidade Estadual de Londrina  
- **Yves Rafael Bovolenta**, Universidade Estadual de Londrina  
- **Rodolfo de Abreu**, USP-ESALQ  
- **Simone Athayde**, Instituto Socioambiental  
- **Rita Quitete Portela**, UNICAMP  
- **Camilla Castanho**, Universidade de São Paulo  

### Sabbatical Visitors

- **Karine Carvalho**, Universidade Federal do Sul da Bahia  
- **Ariadna V. F. Lopes**, Universidade Federal de Pernambuco  
- **Alexandre Oliveira,** Universidade de São Paulo  
- **Laury Cullen**, Instituto de Pesquisas Ecologicas (IPÊ)  

### Technicians

- **Laura Vivian Barbosa:** Laura was responsible for coordinating field work in the Cerrado. She went on to earn a PhD from the Universidade Federal de Uberlandia.

- **Paulo Rubim:** Paulo was responsible for coordinating field work at the BDFFP. He went on to earn a PhD from the Universidade Federal de Sao Carlos.

- **Sylvia Heredia:** Sylvia was responsible for coordinating field work on ant-plant mutualisms at the BDFFP. She went on to earn a PhD from the Universidade of California, Riverside.

- **Maria Rosa Darrigo:** Rosinha was responsible for coordinating field work at the BDFFP. She went on to earn a PhD from the University of Campinas.

- **Simone Benedet Fontoura:** Simone was responsible for coordinating field work at the BDFFP. She went on to earn a PhD from the Universidade Federal de Lavras

- **Polyanna Custodio Duarte:** Polyanna was responsible for coordinating field work in the Cerrado. She was a graduate student at ESALq


<!-- ::: -->
<!-- :::{.sand-background} -->
